export { default as registerRoute } from "./auth/register.routes.js";
export { default as loginRoute } from "./auth/login.routes.js";
export { default as createBlogRoute } from "./blog/createBlog.routes.js";
export { default as deleteBlogRoute } from "./blog/deleteBlog.routes.js";
export { default as updateBlogRoute } from "./blog/updateBlog.routes.js";
export { default as getAllBlogsRoute } from "./blog/getAllBlogs.routes.js";
export { default as getBlogRoute } from "./blog/getBlog.routes.js";
export { default as getBlogByUserRoute } from "./blog/getBlogByUser.routes.js";
export { default as updateUserRoute } from "./auth/updateUser.routes.js";